FROM node:25-alpine3.21

ARG BACKEND_PORT

WORKDIR /backend
COPY package.json .

# Cache package installation
RUN yarn

COPY src ./src
COPY tsconfig.json .

EXPOSE $BACKEND_PORT
ENV NODE_ENV='development'

CMD ["yarn", "dev"]
